// <auto-generated />
using System;
using Infraestrutura.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(VestibularContext))]
    partial class VestibularContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("CadernoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Pontuacao")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CadernoId");

                    b.ToTable("aluno_tb", (string)null);
                });

            modelBuilder.Entity("Core.Caderno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("caderno_tb", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Caderno do Vestibular 2024",
                            Nome = "Caderno Azul"
                        });
                });

            modelBuilder.Entity("Core.Prova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CadernoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.HasIndex("CadernoId");

                    b.ToTable("prova_tb", (string)null);
                });

            modelBuilder.Entity("Core.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("CadernoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NumeroQuestao")
                        .HasColumnType("int");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("CadernoId");

                    b.ToTable("questao_tb", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativaA = "3",
                            AlternativaB = "4",
                            AlternativaC = "5",
                            AlternativaD = "6",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 2 + 2?",
                            NumeroQuestao = 1,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 2,
                            AlternativaA = "3",
                            AlternativaB = "4",
                            AlternativaC = "5",
                            AlternativaD = "6",
                            CadernoId = 1,
                            Descricao = "Qual é a raiz quadrada de 16?",
                            NumeroQuestao = 2,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 3,
                            AlternativaA = "10",
                            AlternativaB = "12",
                            AlternativaC = "15",
                            AlternativaD = "20",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 3 * 5?",
                            NumeroQuestao = 3,
                            RespostaCorreta = "C"
                        },
                        new
                        {
                            Id = 4,
                            AlternativaA = "2",
                            AlternativaB = "3",
                            AlternativaC = "4",
                            AlternativaD = "5",
                            CadernoId = 1,
                            Descricao = "Quanto é 9 dividido por 3?",
                            NumeroQuestao = 4,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 5,
                            AlternativaA = "2",
                            AlternativaB = "3",
                            AlternativaC = "4",
                            AlternativaD = "5",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 7 - 4?",
                            NumeroQuestao = 5,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 6,
                            AlternativaA = "14",
                            AlternativaB = "16",
                            AlternativaC = "18",
                            AlternativaD = "20",
                            CadernoId = 1,
                            Descricao = "Qual é o dobro de 8?",
                            NumeroQuestao = 6,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 7,
                            AlternativaA = "2",
                            AlternativaB = "4",
                            AlternativaC = "5",
                            AlternativaD = "6",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 10 / 2?",
                            NumeroQuestao = 7,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 8,
                            AlternativaA = "10",
                            AlternativaB = "12",
                            AlternativaC = "14",
                            AlternativaD = "16",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 4 * 3?",
                            NumeroQuestao = 8,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 9,
                            AlternativaA = "3",
                            AlternativaB = "4",
                            AlternativaC = "5",
                            AlternativaD = "6",
                            CadernoId = 1,
                            Descricao = "Quanto é 25 dividido por 5?",
                            NumeroQuestao = 9,
                            RespostaCorreta = "C"
                        },
                        new
                        {
                            Id = 10,
                            AlternativaA = "6",
                            AlternativaB = "9",
                            AlternativaC = "12",
                            AlternativaD = "15",
                            CadernoId = 1,
                            Descricao = "Qual é o resultado da expressão 3^2?",
                            NumeroQuestao = 10,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 11,
                            AlternativaA = "Casa",
                            AlternativaB = "Comida",
                            AlternativaC = "Correr",
                            AlternativaD = "Livro",
                            CadernoId = 1,
                            Descricao = "Qual das palavras abaixo é um verbo?",
                            NumeroQuestao = 11,
                            RespostaCorreta = "C"
                        },
                        new
                        {
                            Id = 12,
                            AlternativaA = "Cachorros",
                            AlternativaB = "Cachorroes",
                            AlternativaC = "Cachorrões",
                            AlternativaD = "Cachorroz",
                            CadernoId = 1,
                            Descricao = "Qual é o plural de 'cachorro'?",
                            NumeroQuestao = 12,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 13,
                            AlternativaA = "Feliz",
                            AlternativaB = "Triste",
                            AlternativaC = "Contente",
                            AlternativaD = "Radiante",
                            CadernoId = 1,
                            Descricao = "Qual é o antônimo de 'alegre'?",
                            NumeroQuestao = 13,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 14,
                            AlternativaA = "O",
                            AlternativaB = "A",
                            AlternativaC = "Os",
                            AlternativaD = "As",
                            CadernoId = 1,
                            Descricao = "Qual é o artigo definido masculino singular?",
                            NumeroQuestao = 14,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 15,
                            AlternativaA = "Folhas",
                            AlternativaB = "Folhax",
                            AlternativaC = "Folhões",
                            AlternativaD = "Folhaes",
                            CadernoId = 1,
                            Descricao = "Qual é o plural de 'folha'?",
                            NumeroQuestao = 15,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 16,
                            AlternativaA = "Andando",
                            AlternativaB = "Andido",
                            AlternativaC = "Andava",
                            AlternativaD = "Andou",
                            CadernoId = 1,
                            Descricao = "Qual é a forma verbal correta?",
                            NumeroQuestao = 16,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 17,
                            AlternativaA = "Cavalona",
                            AlternativaB = "Cavalona",
                            AlternativaC = "Cavalina",
                            AlternativaD = "Cavala",
                            CadernoId = 1,
                            Descricao = "Qual é o feminino de 'cavalo'?",
                            NumeroQuestao = 17,
                            RespostaCorreta = "D"
                        },
                        new
                        {
                            Id = 18,
                            AlternativaA = "Bolões",
                            AlternativaB = "Bolas",
                            AlternativaC = "Bolões",
                            AlternativaD = "Bolões",
                            CadernoId = 1,
                            Descricao = "Qual é o plural de 'bola'?",
                            NumeroQuestao = 18,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 19,
                            AlternativaA = "Claro",
                            AlternativaB = "Opaco",
                            AlternativaC = "Negro",
                            AlternativaD = "Obscuro",
                            CadernoId = 1,
                            Descricao = "Qual é o antônimo de 'escuro'?",
                            NumeroQuestao = 19,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 20,
                            AlternativaA = "Livros",
                            AlternativaB = "Livres",
                            AlternativaC = "Livroes",
                            AlternativaD = "Livrões",
                            CadernoId = 1,
                            Descricao = "Qual é o plural de 'livro'?",
                            NumeroQuestao = 20,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 21,
                            AlternativaA = "Buenos Aires",
                            AlternativaB = "Rio de Janeiro",
                            AlternativaC = "Brasília",
                            AlternativaD = "São Paulo",
                            CadernoId = 1,
                            Descricao = "Qual é a capital do Brasil?",
                            NumeroQuestao = 21,
                            RespostaCorreta = "C"
                        },
                        new
                        {
                            Id = 22,
                            AlternativaA = "Brasil",
                            AlternativaB = "Rússia",
                            AlternativaC = "China",
                            AlternativaD = "Estados Unidos",
                            CadernoId = 1,
                            Descricao = "Qual é o maior país do mundo em extensão territorial?",
                            NumeroQuestao = 22,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 23,
                            AlternativaA = "Amazonas",
                            AlternativaB = "Tietê",
                            AlternativaC = "São Francisco",
                            AlternativaD = "Paraná",
                            CadernoId = 1,
                            Descricao = "Qual é o principal rio do Brasil?",
                            NumeroQuestao = 23,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 24,
                            AlternativaA = "Monte Kilimanjaro",
                            AlternativaB = "Monte Everest",
                            AlternativaC = "Monte Fuji",
                            AlternativaD = "Monte Aconcágua",
                            CadernoId = 1,
                            Descricao = "Qual é o ponto mais alto do mundo?",
                            NumeroQuestao = 24,
                            RespostaCorreta = "B"
                        },
                        new
                        {
                            Id = 25,
                            AlternativaA = "Ásia",
                            AlternativaB = "África",
                            AlternativaC = "Europa",
                            AlternativaD = "Austrália",
                            CadernoId = 1,
                            Descricao = "Qual é o menor continente do mundo?",
                            NumeroQuestao = 25,
                            RespostaCorreta = "D"
                        },
                        new
                        {
                            Id = 26,
                            AlternativaA = "Tóquio",
                            AlternativaB = "Nova York",
                            AlternativaC = "Cidade do México",
                            AlternativaD = "Xangai",
                            CadernoId = 1,
                            Descricao = "Qual é a cidade mais populosa do mundo?",
                            NumeroQuestao = 26,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 27,
                            AlternativaA = "Deserto do Saara",
                            AlternativaB = "Deserto do Atacama",
                            AlternativaC = "Deserto da Arábia",
                            AlternativaD = "Deserto de Gobi",
                            CadernoId = 1,
                            Descricao = "Qual é o deserto mais quente do mundo?",
                            NumeroQuestao = 27,
                            RespostaCorreta = "A"
                        },
                        new
                        {
                            Id = 28,
                            AlternativaA = "Japão",
                            AlternativaB = "Estados Unidos",
                            AlternativaC = "Indonésia",
                            AlternativaD = "Itália",
                            CadernoId = 1,
                            Descricao = "Qual é o país que possui mais vulcões ativos?",
                            NumeroQuestao = 28,
                            RespostaCorreta = "C"
                        },
                        new
                        {
                            Id = 29,
                            AlternativaA = "Havaí",
                            AlternativaB = "Maldivas",
                            AlternativaC = "Filipinas",
                            AlternativaD = "Indonésia",
                            CadernoId = 1,
                            Descricao = "Qual é o maior arquipélago do mundo?",
                            NumeroQuestao = 29,
                            RespostaCorreta = "D"
                        },
                        new
                        {
                            Id = 30,
                            AlternativaA = "Rússia",
                            AlternativaB = "Estados Unidos",
                            AlternativaC = "Brasil",
                            AlternativaD = "Reino Unido",
                            CadernoId = 1,
                            Descricao = "Qual é o único país do mundo que está presente em todos os continentes?",
                            NumeroQuestao = 30,
                            RespostaCorreta = "A"
                        });
                });

            modelBuilder.Entity("Core.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativaEscolhida")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("NumeroQuestao")
                        .HasColumnType("int");

                    b.Property<int>("ProvaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvaId");

                    b.ToTable("resposta_tb", (string)null);
                });

            modelBuilder.Entity("Core.Aluno", b =>
                {
                    b.HasOne("Core.Caderno", "Caderno")
                        .WithMany()
                        .HasForeignKey("CadernoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caderno");
                });

            modelBuilder.Entity("Core.Prova", b =>
                {
                    b.HasOne("Core.Aluno", "Aluno")
                        .WithOne("Prova")
                        .HasForeignKey("Core.Prova", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Caderno", "Caderno")
                        .WithMany("Provas")
                        .HasForeignKey("CadernoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Caderno");
                });

            modelBuilder.Entity("Core.Questao", b =>
                {
                    b.HasOne("Core.Caderno", "Caderno")
                        .WithMany("Questoes")
                        .HasForeignKey("CadernoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Caderno");
                });

            modelBuilder.Entity("Core.Resposta", b =>
                {
                    b.HasOne("Core.Prova", "Prova")
                        .WithMany("Respostas")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prova");
                });

            modelBuilder.Entity("Core.Aluno", b =>
                {
                    b.Navigation("Prova")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Caderno", b =>
                {
                    b.Navigation("Provas");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("Core.Prova", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
